### PR TITLE
feat: Show the enable/disable keyboard shortcut in the menu ⌨️

### PR DESCRIPTION
**Pull request by pvinis**
Screenshot 2023-01-29 at 01 42 04

### CODE REVIEW

**Comment by jbmorley** [comment]
This is a great idea; thanks! 🎉

**Comment by jbmorley** [comment]
Oops. Sorry about closing that.

**Comment by jbmorley** [comment]
I've spent a lot of time trying to figure out why this PR didn't run cleanly (and in the process determined that we should probably have never let it run in the first place), but little time looking at the PR itself. So, here's some comments on the PR.

**General**

- Please use sentence case in pull request titles; these are going to end up in the release notes and it'd be great to keep them looking consistent (I've updated this one already)
- I strongly encourage the use of emoji in PR titles; they keep something quite boring a little more fun (I try to remember myself, but often forget)

**Style**

I should probably have a code style guide somewhere for InSeven, but this will have to suffice.

- Avoid chaining SwiftUI modifiers; putting each on a new line makes it much easier to quickly glance over the code and see the styles that have been applied

**Specific**

I'd love to keep the visual style a little more minimal and in keeping with macOS generally. Always open to interpretation but, in this case, I think that means:

- `.foregroundColor(.secondary)` for secondary text (esp. keyboard shortcuts)
- Don't spell out the special keys; the symbols are good enough for this. In this particular case, that means I think I'd simply drop the second line completely
- It looks like there's a very explicit ordering of these modifiers; in this case I _think_ it should be ctrl, opt, then cmd

I'm actually struggling a little to think how this should look beyond those high-level thoughts. What do you think about making it something like:

```swift
HStack {
    Text("Enable/Disable Capture")
    Spacer()
    Text("⌃⌥⌘K")
}
.foregroundColor(.secondary)
```

(I don't really have a good sense of this would make more sense as `.body`, or `.caption` as you have it here. I'd lean towards leaving it as body (no modifier) and seeing how it looks, especially since it's using the secondary foreground color.)

That would have the effect of sitting it aligned below the toggle switch and also looking a lot like a regular menu.

**Comment by pvinis** [comment]
closed in favour of https://github.com/inseven/tinyboard/pull/35

**Pull request closed without merging**
